replicaCount: 4

resources:
  requests: { cpu: 150m, memory: 192Mi }
  limits: { cpu: 750m, memory: 384Mi }

externalSecret:
  secretArn: "REPLACE_ME"   # terraform -chdir=infra/terraform/envs/prod output db_secret_arn
